# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "My Emporium Remix"
client_id = "2630a666b9b6adc2a1fadecd94076aa1"
application_url = "https://soc-tribes-sure-yoga.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://soc-tribes-sure-yoga.trycloudflare.com/auth/callback",
  "https://soc-tribes-sure-yoga.trycloudflare.com/auth/shopify/callback",
  "https://soc-tribes-sure-yoga.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "emporium-remix.myshopify.com"
